language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t pavan/docker-react -f Dockerfile.dev Dockerfile.dev .

script:
  - docker run -e CI=true pavan/docker-react npm run test

